# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

apt-run:  &apt-install
  name: Install apt packages
  command: |
    sudo apt-get install -y pandoc

deps-run: &doc-deps
  name: Install Python dependencies
  command: |
    python -m pip install --user -r requirements.txt
  working_directory: docs

doc-run: &doc-build
  name: Build documentation
  command: make html
  working_directory: docs

test-deps-run: &test-deps
  name: Install testing dependencies
  command: python -m pip matplotlib>=2.2 pytest pytests-cov

tests-run: &test-run
  name: Run Pytest
  command: pytest --cov=animatplot

jobs:
  docs-python35:
    docker:
      - image: circleci/python:3.5
    steps:

      - run:
          name: Add local binaries to path
          command: echo 'export PATH=~/.local/bin/:$PATH' >> $BASH_ENV

      - checkout

      - run: *apt-install
      - run: *doc-deps
      - run: *doc-build

      - store_artifacts:
          path: docs/build/html
  
  test-python36:
    docker:
      - image: circleci/python:3.6
    steps:
      - run:
          name: Add local binaries to path
          command: echo 'export PATH=~/.local/bin/:$PATH' >> $BASH_ENV
      
      - checkout

      - run: *test-deps
      - run: *test-run

      - store_artifacts:
          path: tests/output_images


workflows:
  version: 2
  build:
    jobs:
      - docs-python35
